# Generated by Django 4.2.7 on 2025-11-18 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityEdit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Untitled City', max_length=200)),
                ('grid_data', models.JSONField(default=list)),
                ('rows', models.IntegerField(default=16)),
                ('cols', models.IntegerField(default=25)),
                ('selected_tool', models.CharField(default='select', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
